flowchart TD
    A[Home Router / Main Internet] --> B[Mini Switch]
    B --> C[TP-Link Archer C6 Router]
    C --> D[SilverHomeLab Wi-Fi / Lab Network]
    D --> E[Laptop 1 Admin Workstation]
    C --> F[LAN Port to USB-to-LAN Adapter: nic1]
    F --> G[Proxmox Host: Laptop 2]
    G --> H[vmbr0 Bridge]
    H --> I[Ubuntu Server VM: SilverServer-Ubuntu]
    H --> J[Future VM: Windows Server]
    H --> K[Future VM: Kali / Security Tools]
    L[Tailscale Secure Remote Access] -.-> G
